name: foto
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera_android: ^0.10.9
  camera_avfoundation: ^0.9.15
  camera_platform_interface: ^2.6.0
  camera_web: ^0.3.3
  flutter_plugin_android_lifecycle: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  plugin_platform_interface: ^2.1.7

flutter:
  # Menghapus bagian plugin dari sini
